export const FIXTURES_API_BASE = '/fixtures'
export const LEADERBOARD_API_BASE = '/leaderboard'
export const PLAYERS_API_BASE = '/players'
export const TEAMS_API_BASE = '/team'
export const FRANCHISE_API_BASE = '/franchise'
export const ADMIN_API_BASE = '/admin'
export const DASHBOARD_API_BASE = '/dashboard'
export const USERS_API_BASE = '/users'
