// import type { Player } from '@/features/team-builder/types/players'

// export const playersData: Player[] = [
//     {
//         id: '1',
//         playerId: 101,
//         name: 'Virat Kohli',
//         team: 'RCB',
//         role: 'Batsman',
//         credits: 100,
//         creditValue: 10,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/virat.png',
//         totalFantasyPoints: 250
//     },
//     {
//         id: '2',
//         playerId: 102,
//         name: 'Jasprit Bumrah',
//         team: 'MI',
//         role: 'Bowler',
//         credits: 90,
//         creditValue: 9,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/bumrah.png',
//         totalFantasyPoints: 220
//     },
//     {
//         id: '3',
//         playerId: 103,
//         name: 'AB de Villiers',
//         team: 'RCB',
//         role: 'Batsman',
//         credits: 95,
//         creditValue: 9.5,
//         isOverseas: true,
//         playerImageUrl: 'https://example.com/abd.png',
//         totalFantasyPoints: 240
//     },
//     {
//         id: '4',
//         playerId: 104,
//         name: 'Rashid Khan',
//         team: 'SRH',
//         role: 'Bowler',
//         credits: 85,
//         creditValue: 8.5,
//         isOverseas: true,
//         playerImageUrl: 'https://example.com/rashid.png',
//         totalFantasyPoints: 210
//     },
//     {
//         id: '5',
//         playerId: 105,
//         name: 'Hardik Pandya',
//         team: 'MI',
//         role: 'All-Rounder',
//         credits: 92,
//         creditValue: 9.2,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/hardik.png',
//         totalFantasyPoints: 230
//     },
//     {
//         id: '6',
//         playerId: 106,
//         name: 'Glenn Maxwell',
//         team: 'RCB',
//         role: 'All-Rounder',
//         credits: 88,
//         creditValue: 8.8,
//         isOverseas: true,
//         playerImageUrl: 'https://example.com/maxwell.png',
//         totalFantasyPoints: 215
//     },
//     {
//         id: '7',
//         playerId: 107,
//         name: 'Ruturaj Gaikwad',
//         team: 'CSK',
//         role: 'Batsman',
//         credits: 60,
//         creditValue: 6,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/ruturaj.png',
//         totalFantasyPoints: 145
//     },
//     {
//         id: '8',
//         playerId: 108,
//         name: 'Shubman Gill',
//         team: 'GT',
//         role: 'Batsman',
//         credits: 58,
//         creditValue: 5.8,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/gill.png',
//         totalFantasyPoints: 138
//     },
//     {
//         id: '9',
//         playerId: 109,
//         name: 'Ishan Kishan',
//         team: 'MI',
//         role: 'Wicket-Keeper',
//         credits: 56,
//         creditValue: 5.6,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/ishan.png',
//         totalFantasyPoints: 132
//     },
//     {
//         id: '10',
//         playerId: 110,
//         name: 'Yuzvendra Chahal',
//         team: 'RR',
//         role: 'Bowler',
//         credits: 55,
//         creditValue: 5.5,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/chahal.png',
//         totalFantasyPoints: 128
//     },
//     {
//         id: '11',
//         playerId: 111,
//         name: 'Kuldeep Yadav',
//         team: 'DC',
//         role: 'Bowler',
//         credits: 54,
//         creditValue: 5.4,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/kuldeep.png',
//         totalFantasyPoints: 125
//     },
//     {
//         id: '12',
//         playerId: 112,
//         name: 'Washington Sundar',
//         team: 'SRH',
//         role: 'All-Rounder',
//         credits: 53,
//         creditValue: 5.3,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/washington.png',
//         totalFantasyPoints: 121
//     },
//     {
//         id: '13',
//         playerId: 113,
//         name: 'Rahul Tripathi',
//         team: 'SRH',
//         role: 'Batsman',
//         credits: 52,
//         creditValue: 5.2,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/tripathi.png',
//         totalFantasyPoints: 118
//     },
//     {
//         id: '14',
//         playerId: 114,
//         name: 'Rinku Singh',
//         team: 'KKR',
//         role: 'Batsman',
//         credits: 51,
//         creditValue: 5.1,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/rinku.png',
//         totalFantasyPoints: 116
//     },
//     {
//         id: '15',
//         playerId: 115,
//         name: 'Mukesh Kumar',
//         team: 'DC',
//         role: 'Bowler',
//         credits: 50,
//         creditValue: 5,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/mukesh.png',
//         totalFantasyPoints: 110
//     },
//     {
//         id: '16',
//         playerId: 116,
//         name: 'Harpreet Brar',
//         team: 'PBKS',
//         role: 'All-Rounder',
//         credits: 48,
//         creditValue: 4.8,
//         isOverseas: false,
//         playerImageUrl: 'https://example.com/harpreet.png',
//         totalFantasyPoints: 104
//     },
//     {
//         id: '17',
//         playerId: 117,
//         name: 'Michael Hussey',
//         team: 'LSG',
//         role: 'Batsman',
//         credits: 46,
//         creditValue: 4.6,
//         isOverseas: true,
//         playerImageUrl: 'https://example.com/michael.png',
//         totalFantasyPoints: 100
//     }
// ]
